### ISSUE TITLE
The command to copy the table does not work

### ISSUE THREAD

**Issue by cary-rowen** [mltony/nvda-tonys-enhancements#16]
Hi tony,
* NVDA2022.4
* Add-on Version: 1.14

An error is thrown when using the copy table command:

```
IO - inputCore.executeGesture (11:02:53.551) - winInputHook (6292):
Input: kb(laptop):alt+NVDA+t
ERROR - scriptHandler.executeScript (11:02:53.575) - MainThread (19832):
error executing script: <bound method GlobalPlugin.injectTableFunction.<locals>.<lambda> of <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x12203990>> with gesture 'alt+NVDA+t'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 289, in executeScript
  File "C:\Users\cary\AppData\Roaming\nvda\addons\tonysEnhancements\globalPlugins\tonysEnhancements\__init__.py", line 1587, in <lambda>
    script = lambda self,gesture: function(self, gesture, *args, **kwargs)
  File "C:\Users\cary\AppData\Roaming\nvda\addons\tonysEnhancements\globalPlugins\tonysEnhancements\__init__.py", line 912, in copyTablePopup
    tableID, row, col, origRowSpan, origColSpan = selfself._getTableCellCoords(selfself.selection)
TypeError: cannot unpack non-iterable _TableCell object
```

**Comment by mltony** [comment]
This is probably compatibility issue - it conflicts with my own PR to 
NVDA core. I will eventually get to this.

**Comment by cary-rowen** [comment]
OK, Thanks
