### ISSUE TITLE
Error with insert detection mode when writing in some edit fields

### ISSUE THREAD

**Issue by CyrilleB79** [mltony/nvda-tonys-enhancements#20]
Hello Tony

You probably do not have time to work on this now. But I log here this error for later if possible.

### STR
1. Enable insert mode detection
2. Go to an edit field such as WordPad document or "To"/"Cc" fields in Outlook
3. 3. Start typing

### Actual result
When you type the first character, you get this error:

```
ERROR - eventHandler.executeEvent (17:50:52.024) - MainThread (22960):
error executing event: caret on <NVDAObjects.Dynamic_EditableTextLogContainerIAccessibleRichEdit50WindowNVDAObject object at 0x0E8D4F70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1719, in event_caret
  File "NVDAObjects\window\edit.pyc", line 884, in event_caret
  File "NVDAObjects\behaviors.pyc", line 306, in event_caret
  File "editableText.pyc", line 388, in detectPossibleSelectionChange
  File "editableText.pyc", line 395, in _updateSelectionAnchor
  File "textInfos\offsets.pyc", line 534, in compareEndPoints
AttributeError: 'ITextDocumentTextInfo' object has no attribute '_startOffset'
```

This happens only with the first keystroke. Then no more error

### Expected result:
No error

### Investigation

The error is caused by the call of `getCurrentLineAndCaret`, more specifically by the call of:
`caretInfo = focus.makeTextInfo(textInfos.POSITION_SELECTION)`

There should be some sort of collateral effect, but I have not been able to investigate further.
If you have an idea (since you have written this code), let me know.

**Comment by CyrilleB79** [comment]
Additional information:
Here is a real-life consequence of this error:
If I configure document settings to report Alignment of paragraphs (left, centered, right, justify) and if I write in a Wordpad document, the paragraph alignments are not reported anymore.

**Comment by cary-rowen** [comment]
Hi @mltony 
Do you have any suggestions for this?

**Comment by mltony** [comment]
Not really, this requires investigation. I wrote this code many years ago, so I don't remember anymore why I had to use _startOffset in that code.
